/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colorextractor.ui;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Karanja
 */
public class JPanelMenu extends javax.swing.JPanel {

    private final Color org;

    /**
     * Creates new form JPanelMenu
     */
    public JPanelMenu() {
        initComponents();
        org = jButtonExit.getBackground();

    }
    /**
     * Add ActionListener to Exit Button
     *
     * @param al
     */
    public void addBtnExitActionListener(ActionListener al) {
        jButtonExit.addActionListener(al);
    }

    /**
     * *
     * Add mouse listener for all the buttons on the top panel
     *
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonExit1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 0));

        jButtonExit.setBackground(new java.awt.Color(255, 153, 0));
        jButtonExit.setText("<html><p align=\"center\">Developed By S.Karanja<br>\nAll Rights Reserved &copy;2015\nFor Sourcecode, Email simonkiruku@gmail.com.\nFile Filtering by Edwin Agik.\nReviewed by Mark Kiptoo\n</p>");
        jButtonExit.setBorderPainted(false);
        jButtonExit.setContentAreaFilled(false);
        jButtonExit.setFocusPainted(false);
        jButtonExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExit.setOpaque(true);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jButtonExit1.setBackground(new java.awt.Color(255, 153, 0));
        jButtonExit1.setText("<html><p align=\"center\">A Java based application, that extract\nper pixel RGB and HEX color values from an image, by hovering the mouse on the desired\nimage portion.\n</p>");
        jButtonExit1.setBorderPainted(false);
        jButtonExit1.setContentAreaFilled(false);
        jButtonExit1.setFocusPainted(false);
        jButtonExit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExit1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jButtonExit1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExit1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
